### ISSUE TITLE
strictly follow the tutorial, the last step did not show the correct result?

### ISSUE THREAD

**Issue by eruca** [apple/swift-getting-started-cli#4]
I really new to  swift lang, I want to learn some new languages.
I strictly follow the steps, all steps succeed except the last one,
I run it on my MacStudio with swift 5.9, why it did not print the correct result It should be.
```bash
(base) ➜  MyCLI swift run MyCLI --input "hello, world"
Building for debugging...
Build complete! (0.08s)
USAGE: figlet-tool --input <input>

OPTIONS:
  --input <input>         Specify the input
  -h, --help              Show help information.
```

**Comment by 0xTim** [comment]
@eruca does `swift run MyCLI -h` show the correct output? And have you tried running the code from this library to see if it works?

**Comment by eruca** [comment]
```bash
(base) ➜  MyCLI swift run MyCLI -h
Building for debugging...
Build complete! (0.32s)
USAGE: figlet-tool --input <input>

OPTIONS:
  --input <input>         Specify the input
  -h, --help              Show help information.

(base) ➜  MyCLI ls
Package.resolved Package.swift    Sources
(base) ➜  MyCLI pwd
/Users/nick/Codings/Swift/examples/MyCLI
(base) ➜  MyCLI swift run MyCLI --input "hello, world"
Building for debugging...
Build complete! (0.10s)
USAGE: figlet-tool --input <input>

OPTIONS:
  --input <input>         Specify the input
  -h, --help              Show help information.```

**Comment by eruca** [comment]
I have learned some of the Rust,  it has the certainly usage, like ```cargo run -- --input "hello, world"```, so I did not get the correct answer, I want to know why?

**Comment by 0xTim** [comment]
@eruca just to confirm the output in the comment is from the cloned repo and not the one you created using the tutorial?

**Comment by eruca** [comment]
you're right, it run well if I clone the repo! thanks a lot!
any reasons? 
Or how to configure the project to fix the bug

**Comment by 0xTim** [comment]
My suggestion would be to compare the 2 codebases and see. You might have missed registering the flag or something

**Comment by eruca** [comment]
Thanks a lot
